### ISSUE TITLE
Have a look at danigb/tonal

### ISSUE THREAD

**Issue by nicokaiser** [nicokaiser/bandoneon#1]
Maybe the danigb/tonal libraries provide useful functions

**Comment by behinger** [comment]
Tonal-support was pretty easy, thanks for the tipp. I added it here:
https://github.com/behinger/bandoneon/blob/gh-pages/js/app/chords_tonal.js

You also need to import it for node-js & I renamed some of the chords to follow "scientific"-notation (albeit I still have not much clue on chords...).

**Comment by nicokaiser** [comment]
I moved to @tonaljs/chords yesterday and show all chord notes instead of specific ones. Not sure if this is a good idea, but after playing in tango groups, it came quite useful to see all chord notes instead of one specific transposition.

**Comment by behinger** [comment]
Cool! I will at some point fork it again. I did something similar for my 144 version. I think it could be helpful to colormark the same notes, i.e. tonic green, fifth red etc. not sure it would be the best system, but usually you don't want to double the same note (as far as I know)
