### ISSUE TITLE
Support for Einheitsbandoneon

### ISSUE THREAD

**Issue by nicokaiser** [nicokaiser/bandoneon#2]
The app should provide pluggable layouts, to support e.g. the "Einheitsbandoneon" layout.

![bass diskant](https://cloud.githubusercontent.com/assets/238631/18489383/8d42a990-79fd-11e6-93fd-99373b0054f6.jpg)

**Comment by behinger** [comment]
as I'm about to upgrade from a concertina; can I help to make this happen?

**Comment by behinger** [comment]
For anyone interested, a modified layout for the 144 bandoneon can be found here: https://github.com/behinger/bandoneon/blob/gh-pages/js/app/layout.js

**Comment by nicokaiser** [comment]
That's awesome! I'm currently working on a more modular approach where you can change the instrument, so I will include your layout if that's okay!

**Comment by behinger** [comment]
absolutely :-)
Thanks again for the nice tool, it helped me greatly to learn the bandoneon; 4 month in now :-)

**Comment by nicokaiser** [comment]
This is now supported, along with some other instrument layouts.
